version: "3"
services:
  db:
    container_name: postgresql
    image: ghcr.io/longlangu/dev/postgres-pg-vector:latest
    restart: always
    environment:
      POSTGRES_USER: sakura
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'discordbot-development'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  phppgadmin:
    container_name: phppgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
volumes:
  db_data:
  pgadmin-data: