apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-hackathon-deployment
  namespace: team-hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-hackathon-discord-bot-pod
  template:
    metadata:
      labels:
        app: team-hackathon-discord-bot-pod
    spec:
      containers:
        - name: discord-bot-container
          image: ghcr.io/longlangu/arm32v7/python-dicordbot:latest
          ports:
            - containerPort: 8443
          env:
            - name: ENVIRONMENT
              value: production
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: team-hackathon-discord-bot-secret
                  key: bot-token
                  optional: false
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: team-hackathon-discord-bot-secret
                  key: gemini-api-key
                  optional: false
          resources:
            limits:
              cpu: "60m"
              memory: "128Mi"
          volumeMounts:
            - name: mount
              mountPath: /app
        - name: git-sync
          image: ghcr.io/longlangu/arm32v7/git-sync:v1.1.1
          resources:
            limits:
              cpu: "30m"
              memory: "16Mi"
          env:
            - name: REPO_URL
              value: https://github.com/teamshackathon/discord-bot.git
            - name: BRANCH
              value: main
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: team-hackathon-discord-bot-secret
                  key: discord-webhook
                  optional: false
            - name: POSTGRES_HOST
              value: postgresql-service.discord-db.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: team-hackathon-discord-bot-secret
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: team-hackathon-discord-bot-secret
                  key: postgres_password
            - name: POSTGRES_DB
              value: teamshackathon
          volumeMounts:
            - name: mount
              mountPath: /git/src
      volumes:
        - name: mount
          emptyDir: {}